# Generated by Django 3.0.2 on 2020-01-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('annee', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('pseudo', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('avatar', models.ImageField(upload_to=None)),
                ('email', models.EmailField(max_length=254)),
                ('num_eleve', models.IntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Maquette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('pseudo', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('avatar', models.ImageField(upload_to=None)),
                ('email', models.EmailField(max_length=254)),
                ('num_professeur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professeur_Pedagogique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('pseudo', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('avatar', models.ImageField(upload_to=None)),
                ('email', models.EmailField(max_length=254)),
                ('num_professeur', models.IntegerField()),
                ('num_professeur_pedagogique', models.IntegerField()),
                ('Professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('pseudo', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('avatar', models.ImageField(upload_to=None)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=50)),
                ('maquette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Maquette')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('document', models.FileField(upload_to=None)),
                ('professeur_pedagogique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Professeur_Pedagogique')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('pseudo', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('avatar', models.ImageField(upload_to=None)),
                ('email', models.EmailField(max_length=254)),
                ('num_eleve', models.IntegerField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
                ('professeur_pedagogique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Professeur_Pedagogique')),
            ],
        ),
        migrations.AddField(
            model_name='professeur_pedagogique',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Utilisateur'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Utilisateur'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Utilisateur'),
        ),
        migrations.CreateModel(
            name='EC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('charge_horaire', models.IntegerField()),
                ('coef', models.IntegerField()),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.UE')),
            ],
        ),
        migrations.CreateModel(
            name='Chef_Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('pseudo', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('avatar', models.ImageField(upload_to=None)),
                ('email', models.EmailField(max_length=254)),
                ('num_professeur', models.IntegerField()),
                ('num_chef_departement', models.IntegerField()),
                ('Professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Professeur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Cahier_De_Texte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_EC', models.CharField(max_length=50)),
                ('duree_EC', models.IntegerField()),
                ('nom_professeur', models.IntegerField()),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField()),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Responsable')),
            ],
        ),
    ]
