# Generated by Django 3.0.2 on 2020-02-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahier_de_texte',
            name='classe',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cahier_de_texte',
            name='duree_EC',
            field=models.CharField(max_length=50),
        ),
    ]
