# Generated by Django 3.0.2 on 2020-01-29 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser_Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Classe')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Professeur')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.EC')),
            ],
        ),
    ]
