# Generated by Django 3.0.2 on 2020-02-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
