# Generated by Django 3.0.2 on 2020-02-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_table',
            name='moment',
            field=models.CharField(blank=True, choices=[('Lundi Matin', 'Lundi Soir'), ('Mardi Matin', 'Mardi Soir'), ('Mercredi Matin', 'Mercredi Soir'), ('Jeudi Matin', 'Jeudi Soir'), ('Vendredi Matin', 'Vendredi Soir'), ('Samedi Matin', 'Samedi Soir')], max_length=50, null=True),
        ),
    ]
