# Generated by Django 3.0.2 on 2020-02-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='fonction',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
