# Generated by Django 3.0.2 on 2020-02-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20200223_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField()),
                ('classe', models.CharField(blank=True, max_length=50, null=True)),
                ('ec', models.CharField(blank=True, max_length=50, null=True)),
                ('debut', models.TimeField()),
                ('fin', models.TimeField()),
                ('prof', models.CharField(blank=True, max_length=50, null=True)),
                ('jour', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
