# Generated by Django 3.0.2 on 2020-02-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
