# Generated by Django 3.0.2 on 2020-02-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20200222_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_table',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
