# Generated by Django 3.0.2 on 2020-01-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_dispenser_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahier_de_texte',
            name='nom_professeur',
            field=models.CharField(max_length=50),
        ),
    ]
