# Generated by Django 3.0.2 on 2020-02-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_time_table_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='moment',
            field=models.CharField(blank=True, choices=[('Lundi Matin', 'Lundi Matin'), ('Lundi Soir', 'Lundi Soir'), ('Mardi Matin', 'Mardi Matin'), ('Mardi Soir', 'Mardi Soir'), ('Mercredi Matin', 'Mercredi Matin'), ('Jeudi Matin', 'Jeudi Matin'), ('Vendredi Matin', 'Vendredi Matin'), ('Samedi Matin', 'Samedi Matin'), ('Mercredi Soir', 'Mercredi Soir'), ('Jeudi Soir', 'Jeudi Soir'), ('Vendredi Soir', 'Vendredi Soir'), ('Samedi Soir', 'Samedi Soir')], max_length=50, null=True),
        ),
    ]
