# Generated by Django 3.0.2 on 2020-02-22 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_classe_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Classe'),
        ),
    ]
