# Generated by Django 3.0.2 on 2020-02-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='debut',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
