# Generated by Django 3.0.2 on 2020-02-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200222_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='classe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Classe'),
        ),
    ]
