# Generated by Django 3.0.2 on 2020-02-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200216_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_table',
            name='classe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='ec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='utilisateur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
