# Generated by Django 3.0.2 on 2020-01-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200129_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahier_de_texte',
            name='nom_professeur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chef_departement',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professeur_pedagogique',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
    ]
