# Generated by Django 3.0.2 on 2020-02-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20200226_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
