# Generated by Django 3.0.2 on 2020-02-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20200222_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='classe',
            field=models.CharField(max_length=50),
        ),
    ]
