# Generated by Django 3.0.2 on 2020-02-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20200226_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='nom',
        ),
        migrations.CreateModel(
            name='TimeTableListe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('classe', models.CharField(blank=True, max_length=50, null=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.TimeTable')),
            ],
        ),
    ]
