# Generated by Django 3.0.2 on 2020-02-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20200226_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableliste',
            name='timetable',
        ),
        migrations.AddField(
            model_name='timetable',
            name='timetableliste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.TimeTableListe'),
        ),
    ]
